### ISSUE TITLE
update Fulcrum logo on defiscore.io 

### ISSUE THREAD

**Issue by sneg55** [ConsenSys/defi-score#14]
We recently updated our visual identity, can you please update Fulcrum logo here: 

![image](https://user-images.githubusercontent.com/7769371/69116187-4335b780-0a40-11ea-9674-c4e36cbd9638.png)

Here is our branding assets: https://bzx.network/media-assets

**Comment by sneg55** [comment]
cc @jordanlyall

**Comment by jordanlyall** [comment]
@sneg55 Updated Fulcrum icon on defiscore.io

<img width="332" alt="Screen Shot 2019-11-26 at 9 31 20 AM" src="https://user-images.githubusercontent.com/999289/69657657-91921a00-102f-11ea-88a1-d6ac9509bc26.png">
