### ISSUE TITLE
Scoring for products with underlying lending protocols

### ISSUE THREAD

**Issue by sneg55** [ConsenSys/defi-score#5]
I was wondering what're your thoughts on scoring for products where additional layer of smart contracts used before lending protocol itself? 

Examples:
- idle.finance  
- instadapp

**Comment by jclancy93** [comment]
2nd layer lending products are definitely something we're interested in. We don't have any immediate plans to start scoring them but hope to eventually. One of the biggest factors with lending aggregators is the compounding smart contract risk they introduce. I'm excited to see lending products like Linen & Dharma that will offer stable rates via IR swaps and SC insurance for funds through Nexus.  I think 2nd layer lending products are great as long as the benefit of using them outweighs the risk they add.
